import enum

class FFTInpaint:
    def __init__(self) -> None: ...
    def with_epsilon(self, value: float) -> FFTInpaint: ...
    def with_first_guess(self, value: FirstGuess) -> FFTInpaint: ...
    def with_is_periodic(self, value: bool) -> FFTInpaint: ...
    def with_max_iterations(self, value: int) -> FFTInpaint: ...
    def with_num_threads(self, value: int) -> FFTInpaint: ...
    def with_sigma(self, value: float) -> FFTInpaint: ...

class FirstGuess(enum.Enum):
    ZERO = ...
    ZONAL_AVERAGE = ...

class GaussSeidel:
    def __init__(self) -> None: ...
    def with_epsilon(self, value: float) -> GaussSeidel: ...
    def with_first_guess(self, value: FirstGuess) -> GaussSeidel: ...
    def with_is_periodic(self, value: bool) -> GaussSeidel: ...
    def with_max_iterations(self, value: int) -> GaussSeidel: ...
    def with_num_threads(self, value: int) -> GaussSeidel: ...
    def with_relaxation(self, value: float) -> GaussSeidel: ...

class Loess:
    def __init__(self) -> None: ...
    def with_epsilon(self, value: float) -> Loess: ...
    def with_first_guess(self, value: FirstGuess) -> Loess: ...
    def with_is_periodic(self, value: bool) -> Loess: ...
    def with_max_iterations(self, value: int) -> Loess: ...
    def with_num_threads(self, value: int) -> Loess: ...
    def with_nx(self, value: int) -> Loess: ...
    def with_ny(self, value: int) -> Loess: ...
    def with_value_type(self, value: LoessValueType) -> Loess: ...

class LoessValueType(enum.Enum):
    ALL = ...
    DEFINED = ...
    UNDEFINED = ...

class Multigrid:
    def __init__(self) -> None: ...
    def with_epsilon(self, value: float) -> Multigrid: ...
    def with_first_guess(self, value: FirstGuess) -> Multigrid: ...
    def with_is_periodic(self, value: bool) -> Multigrid: ...
    def with_max_iterations(self, value: int) -> Multigrid: ...
    def with_num_threads(self, value: int) -> Multigrid: ...
    def with_post_smooth(self, value: int) -> Multigrid: ...
    def with_pre_smooth(self, value: int) -> Multigrid: ...
