class Bivariate:
    @classmethod
    def bilinear(cls) -> Bivariate: ...
    @classmethod
    def idw(cls) -> Bivariate: ...
    @classmethod
    def nearest(cls) -> Bivariate: ...
    def __init__(self) -> None: ...
    def with_bounds_error(self, value: bool) -> Bivariate: ...
    def with_num_threads(self, value: int) -> Bivariate: ...

class Quadrivariate:
    @classmethod
    def bilinear(cls) -> Quadrivariate: ...
    @classmethod
    def idw(cls) -> Quadrivariate: ...
    @classmethod
    def nearest(cls) -> Quadrivariate: ...
    def __init__(self) -> None: ...
    def with_bounds_error(self, value: bool) -> Quadrivariate: ...
    def with_num_threads(self, value: int) -> Quadrivariate: ...

class Trivariate:
    @classmethod
    def bilinear(cls) -> Trivariate: ...
    @classmethod
    def idw(cls) -> Trivariate: ...
    @classmethod
    def nearest(cls) -> Trivariate: ...
    def __init__(self) -> None: ...
    def with_bounds_error(self, value: bool) -> Trivariate: ...
    def with_num_threads(self, value: int) -> Trivariate: ...
