import enum

class BoundaryCheck(enum.Enum):
    CONVEX_HULL = ...
    ENVELOPE = ...
    NONE = ...

class CovarianceFunction(enum.Enum):
    CAUCHY = ...
    GAUSSIAN = ...
    MATERN_12 = ...
    MATERN_32 = ...
    MATERN_52 = ...
    SPHERICAL = ...
    WENDLAND = ...

class DriftFunction(enum.Enum):
    LINEAR = ...
    QUADRATIC = ...

class InterpolationWindow:
    def __init__(self) -> None: ...
    def with_arg(self, value: float | None) -> InterpolationWindow: ...
    def with_boundary_check(
        self, value: BoundaryCheck
    ) -> InterpolationWindow: ...
    def with_k(self, value: int) -> InterpolationWindow: ...
    def with_num_threads(self, value: int) -> InterpolationWindow: ...
    def with_radius(self, value: float | None) -> InterpolationWindow: ...
    def with_wf(self, value: WindowKernel) -> InterpolationWindow: ...

class InverseDistanceWeighting:
    def __init__(self) -> None: ...
    def with_boundary_check(
        self, value: BoundaryCheck
    ) -> InverseDistanceWeighting: ...
    def with_k(self, value: int) -> InverseDistanceWeighting: ...
    def with_num_threads(self, value: int) -> InverseDistanceWeighting: ...
    def with_p(self, value: int) -> InverseDistanceWeighting: ...
    def with_radius(self, value: float | None) -> InverseDistanceWeighting: ...

class Kriging:
    def __init__(self) -> None: ...
    def with_boundary_check(self, value: BoundaryCheck) -> Kriging: ...
    def with_covariance_model(self, value: CovarianceFunction) -> Kriging: ...
    def with_drift_function(self, value: DriftFunction) -> Kriging: ...
    def with_k(self, value: int) -> Kriging: ...
    def with_lambda(self, value: float) -> Kriging: ...
    def with_nugget(self, value: float) -> Kriging: ...
    def with_num_threads(self, value: int) -> Kriging: ...
    def with_radius(self, value: float | None) -> Kriging: ...
    def with_sigma(self, value: float) -> Kriging: ...

class Query:
    def __init__(self) -> None: ...
    def with_boundary_check(self, value: BoundaryCheck) -> Query: ...
    def with_k(self, value: int) -> Query: ...
    def with_num_threads(self, value: int) -> Query: ...
    def with_radius(self, value: float | None = ...) -> Query: ...

class RBFKernel(enum.Enum):
    CUBIC = ...
    GAUSSIAN = ...
    INVERSE_MULTIQUADRIC = ...
    LINEAR = ...
    MULTIQUADRIC = ...
    THIN_PLATE = ...

class RadialBasisFunction:
    def __init__(self) -> None: ...
    def with_boundary_check(
        self, value: BoundaryCheck
    ) -> RadialBasisFunction: ...
    def with_epsilon(self, value: float | None) -> RadialBasisFunction: ...
    def with_k(self, value: int) -> RadialBasisFunction: ...
    def with_num_threads(self, value: int) -> RadialBasisFunction: ...
    def with_radius(self, value: float | None) -> RadialBasisFunction: ...
    def with_rbf(self, value: RBFKernel) -> RadialBasisFunction: ...
    def with_smooth(self, value: float) -> RadialBasisFunction: ...

class WindowKernel(enum.Enum):
    BLACKMAN = ...
    BLACKMAN_HARRIS = ...
    BOXCAR = ...
    FLAT_TOP = ...
    GAUSSIAN = ...
    HAMMING = ...
    LANCZOS = ...
    NUTTALL = ...
    PARZEN = ...
    PARZEN_SWOT = ...
