class AxisConfig:
    @classmethod
    def linear(cls) -> AxisConfig: ...
    @classmethod
    def nearest(cls) -> AxisConfig: ...
    def __init__(self) -> None: ...

class BoundaryConfig:
    @classmethod
    def shrink(cls) -> BoundaryConfig: ...
    @classmethod
    def undef(cls) -> BoundaryConfig: ...
    def __init__(self) -> None: ...

class Bivariate:
    @classmethod
    def akima(cls) -> Bivariate: ...
    @classmethod
    def akima_periodic(cls) -> Bivariate: ...
    @classmethod
    def bicubic(cls) -> Bivariate: ...
    @classmethod
    def bilinear(cls) -> Bivariate: ...
    @classmethod
    def c_spline(cls) -> Bivariate: ...
    @classmethod
    def c_spline_not_a_knot(cls) -> Bivariate: ...
    @classmethod
    def c_spline_periodic(cls) -> Bivariate: ...
    @classmethod
    def linear(cls) -> Bivariate: ...
    @classmethod
    def polynomial(cls) -> Bivariate: ...
    @classmethod
    def steffen(cls) -> Bivariate: ...
    def __init__(self) -> None: ...
    def with_boundary_mode(self, config: BoundaryConfig) -> Bivariate: ...
    def with_bounds_error(self, value: bool) -> Bivariate: ...
    def with_num_threads(self, value: int) -> Bivariate: ...
    def with_half_window_size_x(self, size: int) -> Bivariate: ...
    def with_half_window_size_y(self, size: int) -> Bivariate: ...

class Quadrivariate:
    @classmethod
    def akima(cls) -> Quadrivariate: ...
    @classmethod
    def akima_periodic(cls) -> Quadrivariate: ...
    @classmethod
    def bicubic(cls) -> Quadrivariate: ...
    @classmethod
    def bilinear(cls) -> Quadrivariate: ...
    @classmethod
    def c_spline(cls) -> Quadrivariate: ...
    @classmethod
    def c_spline_not_a_knot(cls) -> Quadrivariate: ...
    @classmethod
    def c_spline_periodic(cls) -> Quadrivariate: ...
    @classmethod
    def linear(cls) -> Quadrivariate: ...
    @classmethod
    def polynomial(cls) -> Quadrivariate: ...
    @classmethod
    def steffen(cls) -> Quadrivariate: ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Quadrivariate: ...
    def num_threads(self, value: int) -> Quadrivariate: ...
    def with_boundary_mode(self, config: BoundaryConfig) -> Quadrivariate: ...
    def with_bounds_error(self, value: bool) -> Quadrivariate: ...
    def with_fourth_axis(self, config: AxisConfig) -> Quadrivariate: ...
    def with_num_threads(self, value: int) -> Quadrivariate: ...
    def with_third_axis(self, config: AxisConfig) -> Quadrivariate: ...
    def with_half_window_size_x(self, size: int) -> Quadrivariate: ...
    def with_half_window_size_y(self, size: int) -> Quadrivariate: ...

class Trivariate:
    @classmethod
    def akima(cls) -> Trivariate: ...
    @classmethod
    def akima_periodic(cls) -> Trivariate: ...
    @classmethod
    def bicubic(cls) -> Trivariate: ...
    @classmethod
    def bilinear(cls) -> Trivariate: ...
    @classmethod
    def c_spline(cls) -> Trivariate: ...
    @classmethod
    def c_spline_not_a_knot(cls) -> Trivariate: ...
    @classmethod
    def c_spline_periodic(cls) -> Trivariate: ...
    @classmethod
    def linear(cls) -> Trivariate: ...
    @classmethod
    def polynomial(cls) -> Trivariate: ...
    @classmethod
    def steffen(cls) -> Trivariate: ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Trivariate: ...
    def num_threads(self, value: int) -> Trivariate: ...
    def with_boundary_mode(self, config: BoundaryConfig) -> Trivariate: ...
    def with_bounds_error(self, value: bool) -> Trivariate: ...
    def with_num_threads(self, value: int) -> Trivariate: ...
    def with_third_axis(self, config: AxisConfig) -> Trivariate: ...
    def with_half_window_size_x(self, size: int) -> Trivariate: ...
    def with_half_window_size_y(self, size: int) -> Trivariate: ...

class Univariate:
    @classmethod
    def akima(cls) -> Univariate: ...
    @classmethod
    def akima_periodic(cls) -> Univariate: ...
    @classmethod
    def c_spline(cls) -> Univariate: ...
    @classmethod
    def c_spline_not_a_knot(cls) -> Univariate: ...
    @classmethod
    def c_spline_periodic(cls) -> Univariate: ...
    @classmethod
    def linear(cls) -> Univariate: ...
    @classmethod
    def polynomial(cls) -> Univariate: ...
    @classmethod
    def steffen(cls) -> Univariate: ...
    def __init__(self) -> None: ...
    def with_boundary_mode(self, config: BoundaryConfig) -> Univariate: ...
    def with_bounds_error(self, value: bool) -> Univariate: ...
    def with_num_threads(self, value: int) -> Univariate: ...
    def with_half_window_size(self, size: int) -> Univariate: ...
