package:
  name: pyinterp
  version: 0.0.3

source:
    git_url: https://github.com/CNES/pangeo-pyinterp
    git_rev: HEAD

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - eigen
    - gsl
    - libboost
    - numpy
    - python {{ python }}
    - setuptools
    - xarray
  run:
    - numpy
    - python {{ python }}
    - xarray

test:
  imports:
    - pyinterp.core