#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------
import pathlib
import sys
import sysconfig


HERE = pathlib.Path(__file__).absolute().parent
ROOT_DIRECTORY = HERE.parent.parent
MAJOR = sys.version_info[0]
MINOR = sys.version_info[1]


def get_build_dirname():
    """Returns the name of the build directory."""
    path = pathlib.Path(
        ROOT_DIRECTORY,
        "build",
        "lib.%s-%d.%d" % (sysconfig.get_platform(), MAJOR, MINOR),
    )
    if path.exists():
        return path
    return pathlib.Path(
        ROOT_DIRECTORY,
        "build",
        f"lib.{sysconfig.get_platform()}-{sys.implementation.cache_tag}",
    )


build_dirname = get_build_dirname()
if build_dirname.exists():
    sys.path.insert(0, str(build_dirname))

# -- Project information -----------------------------------------------------

project = "pyinterp"
copyright = '(2026, CNES/CLS)'
author = "CNES/CLS"

# The short X.Y version
version = '0.0'
# The full version, including alpha/beta/rc tags
release = '0.0'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_gallery.gen_gallery",
    "sphinx_inline_tabs",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

autosummary_generate = True

# Autodoc configuration for nanobind modules
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
}

# Tell autodoc to use type hints from stub files (.pyi)
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"

# Don't fail on missing type hints
autodoc_type_aliases = {}

numpydoc_class_members_toctree = True
numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"
html_title = "PyInterp"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_theme_options = {
    "logo": {
        "image_light": "_static/pyinterp-light.svg",
        "image_dark": "_static/pyinterp-dark.svg",
    },
    "repository_url": "https://github.com/CNES/pangeo-pyinterp",
    "use_repository_button": True,
}

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "pyinterpdoc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "pyinterp.tex", "PyInterp Documentation", "CLS", "manual"),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "pyinterp", "PyInterp Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "pyinterp",
        "PyInterp Documentation",
        author,
        "pyinterp",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


class SubsectionSorter:
    """Sorts example files within a subsection based on a predefined order."""

    def __init__(self, *args) -> None:
        pass

    def __call__(self, fname):
        order = {
            "ex_objects.py": 0,
            "ex_axis.py": 1,
            "ex_geodetic.py": 2,
            "ex_geohash.py": 3,
            "ex_2d.py": 4,
            "ex_3d.py": 5,
            "ex_4d.py": 6,
            "ex_unstructured.py": 7,
            "ex_orbit.py": 8,
            "pangeo_unstructured_grid.py": 9,
            "pangeo_time_series.py": 10,
            "ex_descriptive_statistics.py": 11,
            "ex_binning.py": 12,
            "ex_dateutils.py": 13,
            "ex_fill_undef.py": 14,
        }
        return order[pathlib.Path(fname).name]


def section_sorter(dirname):
    """Sorts sections based on a predefined order."""
    order = {
        "core": 0,
        "grid": 1,
        "stats": 2,
        "geo": 3,
        "utilities": 4,
        "orbit": 5,
        "pangeo": 6,
    }
    return order[pathlib.Path(dirname).name]


# -- Extension configuration -------------------------------------------------
sphinx_gallery_conf = {
    "examples_dirs": [HERE.parent.parent.joinpath("examples")],
    "filename_pattern": r"[\\\/]ex_",
    "pypandoc": False,
    "subsection_order": section_sorter,
    "within_subsection_order": SubsectionSorter,
    "binder": {
        "org": "CNES",
        "repo": "pangeo-pyinterp",
        "branch": "master",
        "binderhub_url": "https://mybinder.org",
        "dependencies": [
            HERE.joinpath("..", "..", "binder", "environment.yml")
        ],
        "use_jupyter_lab": True,
    },
}

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "dask": ("https://docs.dask.org/en/latest/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
}

README = HERE.joinpath("readme.rst")

if not README.exists():
    with HERE.joinpath("..", "..", "README.rst").open() as stream:
        contents = stream.read()

    with README.open("w") as stream:
        stream.write(contents)


def setup(app) -> None:
    import inspect

    from sphinx.util import inspect as sphinx_inspect

    # Sphinx inspects all objects in the module and tries to resolve their type
    # (attribute, function, class, module, etc.) by using its own functions in
    # `sphinx.util.inspect`. These functions misidentify certain nanobind
    # objects. We monkey patch those functions here.

    def _is_nanobind_func(obj):
        """Check if object is a nanobind function or method."""
        type_name = type(obj).__name__
        return type_name in ("nb_func", "nb_method")

    def _is_nanobind_method(obj):
        """Check if object is a nanobind method."""
        return type(obj).__name__ == "nb_method"

    # Patch isfunction to recognize nb_func
    _orig_isfunction = sphinx_inspect.isfunction

    def mpatch_isfunction(obj):
        if _is_nanobind_func(obj):
            return True
        return _orig_isfunction(obj)

    # Patch ismethod to recognize nb_method
    def mpatch_ismethod(obj):
        if _is_nanobind_method(obj):
            return True
        return inspect.ismethod(obj)

    # Patch isclassmethod
    sphinx_inspect_isclassmethod = sphinx_inspect.isclassmethod

    def mpatch_isclassmethod(obj, cls=None, name=None):
        if _is_nanobind_method(obj):
            return False
        return sphinx_inspect_isclassmethod(obj, cls, name)

    # Patch isstaticmethod - nanobind static methods appear as nb_func
    _orig_isstaticmethod = sphinx_inspect.isstaticmethod

    def mpatch_isstaticmethod(obj, cls=None, name=None):
        # Check if it's a nanobind function in a class context
        if type(obj).__name__ == "nb_func" and cls is not None:
            return True
        return _orig_isstaticmethod(obj, cls, name)

    # Patch iscoroutinefunction
    _orig_iscoroutinefunction = getattr(
        sphinx_inspect, "iscoroutinefunction", None
    )
    if _orig_iscoroutinefunction:

        def mpatch_iscoroutinefunction(obj):
            if _is_nanobind_func(obj):
                return False
            return _orig_iscoroutinefunction(obj)

        sphinx_inspect.iscoroutinefunction = mpatch_iscoroutinefunction

    # Apply patches
    sphinx_inspect.isfunction = mpatch_isfunction
    sphinx_inspect.ismethod = mpatch_ismethod
    sphinx_inspect.isclassmethod = mpatch_isclassmethod
    sphinx_inspect.isstaticmethod = mpatch_isstaticmethod
