# Auto-generated by scripts/generate_geometry_stubs.py. Do not edit.
# Mirrors pyinterp.core.geometry so IDEs resolve the pyinterp.geometry
# import path that pyinterp/__init__.py registers via sys.modules.
from pyinterp.core.geometry.cartesian import *  # noqa: F401,F403
