#!/usr/bin/env python3
# Copyright (c) 2026 CNES.
#
# All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.
"""Generate ``pyinterp/geometry/`` stub shims from ``pyinterp/core/geometry/``.

At runtime, ``pyinterp.__init__`` aliases ``pyinterp.core.geometry`` under the
``pyinterp.geometry`` import path via ``sys.modules``. Static analyzers do not
execute that code, so they do not see ``pyinterp.geometry`` as a real package.

This script mirrors the ``.pyi`` tree under ``pyinterp/core/geometry/`` into
``pyinterp/geometry/`` with thin re-export stubs, restoring IDE / mypy support
without changing runtime behavior.

Run manually after touching ``pyinterp/core/geometry/*.pyi`` (a CI check
enforces the two trees stay in sync), or rely on ``setup.py`` to regenerate
during ``build_py``.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
SRC = REPO / "pyinterp" / "core" / "geometry"
DST = REPO / "pyinterp" / "geometry"

HEADER = (
    "# Auto-generated by scripts/generate_geometry_stubs.py. Do not edit.\n"
    "# Mirrors pyinterp.core.geometry so IDEs resolve the pyinterp.geometry\n"
    "# import path that pyinterp/__init__.py registers via sys.modules.\n"
)


def _module_for(pyi: pathlib.Path) -> str:
    rel = pyi.relative_to(SRC)
    parts = ["pyinterp", "core", "geometry", *rel.parent.parts]
    if pyi.name != "__init__.pyi":
        parts.append(pyi.stem)
    return ".".join(parts)


def _stub_contents(pyi: pathlib.Path) -> str:
    module = _module_for(pyi)
    return f"{HEADER}from {module} import *  # noqa: F401,F403\n"


def _planned_files() -> dict[pathlib.Path, str]:
    return {
        DST / pyi.relative_to(SRC): _stub_contents(pyi)
        for pyi in sorted(SRC.rglob("*.pyi"))
    }


def generate() -> list[pathlib.Path]:
    """Write the stub tree and return the list of files written."""
    plan = _planned_files()
    written: list[pathlib.Path] = []
    for path, contents in plan.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_text() == contents:
            continue
        path.write_text(contents)
        written.append(path)
    return written


def check() -> bool:
    """Return ``True`` when the on-disk tree matches what we would generate."""
    plan = _planned_files()
    existing = {p for p in DST.rglob("*.pyi")}
    if existing != set(plan):
        return False
    return all(path.read_text() == contents for path, contents in plan.items())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated tree is out of sync.",
    )
    args = parser.parse_args(argv)

    if args.check:
        if not check():
            print(
                "pyinterp/geometry/ stubs are out of sync with "
                "pyinterp/core/geometry/. "
                "Run scripts/generate_geometry_stubs.py.",
                file=sys.stderr,
            )
            return 1
        return 0

    written = generate()
    for path in written:
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
