#!/bin/bash
# Copyright (c) 2025 CNES.
#
# This software is distributed by the CNES under a proprietary license.
# It is not public and cannot be redistributed or used without permission.
set -e

# Get working directory of this script
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT=$(realpath ${ROOT}/..)

# Get the number of threads
THREADS=$(getconf _NPROCESSORS_ONLN)

# Get the build temp directory generated by the build script
BUILD_TEMP_DIR=$(python scripts/show_temp_build_dir.py)

# Generate the coverage report
echo "Generating coverage report"
echo "-------------------------------------------------------------------------"
echo "ROOT:           ${ROOT}"
echo "THREADS:        ${THREADS}"
echo "BUILD_TEMP_DIR: ${BUILD_TEMP_DIR}"
echo "-------------------------------------------------------------------------"
cd ${ROOT}

# Python build extension
OS_NAME=$(uname -s)
if [[ "${OS_NAME}" == "Darwin" ]]; then
    echo "Detected macOS - building without MKL"
    python setup.py build_ext --export-compile-commands --enable-coverage
else
    echo "Non-macOS (${OS_NAME}) - building with MKL"
    python setup.py build_ext --export-compile-commands --enable-coverage
fi

# Python build package
python setup.py build

# Run the tests in coverage mode generating the coverage report and create the
# JUnitXML report
pytest -q --cov=build --cov-report=xml:build/coverage_python.xml --junit-xml=build/pybind.xml

# Convert the pytest-cov report to lcov format
coverage lcov -o build/coverage_python.info

# The CMake configuration is already done by the build script in the
# BUILD_TEMP_DIR
cd ${BUILD_TEMP_DIR}

# C++ build & test
make test_all -j ${THREADS}
make lcov -j ${THREADS}
lcov --extract  lcov/data/capture/all_targets.info.raw  "*" -o ../coverage_cpp.info

# Go back to the build directory ${ROOT}/build
cd ..

# Merge the two coverage reports
lcov -a coverage_cpp.info -a coverage_python.info -o coverage.info

# Clean the source file paths in the coverage report
sed -i 's|SF:build/lib\.[^/]*/|SF:|g' coverage.info

# Remove unwanted paths from the final coverage (tests, third_party)
lcov --remove coverage.info "${ROOT}/cxx/tests/*" "${ROOT}/third_party/*" "pyinterp/tests/*" -o coverage.info

# Generate the html report
cd ${ROOT}
genhtml build/coverage.info --output-directory build/htmllcov --prefix "${ROOT}"

# Show the coverage
python scripts/coverage.py build/htmllcov/index.html
