#!/bin/bash
# Copyright (c) 2025 CNES.
#
# This software is distributed by the CNES under a proprietary license.
# It is not public and cannot be redistributed or used without permission.
set -e

# Get working directory of this script
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT=$(realpath ${ROOT}/..)

# Get the number of threads
THREADS=$(getconf _NPROCESSORS_ONLN)

# Get the build temp directory generated by the build script
BUILD_TEMP_DIR=$(python scripts/show_temp_build_dir.py)

# Ensure CMake finds the conda gcov instead of system gcov
# The conda compiler is x86_64-conda-linux-gnu-gcc but gcov is named
# x86_64-conda-linux-gnu-gcov, while CMake-codecov searches for gcov-${VERSION}
CONDA_GCOV=$(which x86_64-conda-linux-gnu-gcov 2>/dev/null)
if [[ -n "${CONDA_GCOV}" ]]; then
    CONDA_BIN_DIR=$(dirname "${CONDA_GCOV}")
    GCC_MAJOR=$(x86_64-conda-linux-gnu-gcc -dumpversion | cut -d. -f1)

    # Create symlinks if they don't exist
    if [[ ! -e "${CONDA_BIN_DIR}/gcov-${GCC_MAJOR}" ]]; then
        ln -s "${CONDA_GCOV}" "${CONDA_BIN_DIR}/gcov-${GCC_MAJOR}"
        echo "Created symlink: gcov-${GCC_MAJOR} -> ${CONDA_GCOV}"
    fi
    if [[ ! -e "${CONDA_BIN_DIR}/gcov" ]]; then
        ln -s "${CONDA_GCOV}" "${CONDA_BIN_DIR}/gcov"
        echo "Created symlink: gcov -> ${CONDA_GCOV}"
    fi
fi

# The capture below relies on options introduced by LCOV 2.0.
LCOV_MAJOR=$(lcov --version | sed -n 's/.*LCOV version \([0-9]*\).*/\1/p')
if [[ "${LCOV_MAJOR:-0}" -lt 2 ]]; then
    echo "LCOV 2.0 or later is required." >&2
    exit 1
fi

# LCOV 2.x rejects the end lines that gcov reports for some functions
# ("mismatched end line"), and the function records of the Python coverage
# ("function is not hit but line is"). Ignore these inconsistencies; the option
# is repeated to also silence the warnings.
LCOV_FLAGS="--ignore-errors inconsistent,inconsistent"

# Generate the coverage report
echo "Generating coverage report"
echo "-------------------------------------------------------------------------"
echo "ROOT:           ${ROOT}"
echo "THREADS:        ${THREADS}"
echo "BUILD_TEMP_DIR: ${BUILD_TEMP_DIR}"
echo "-------------------------------------------------------------------------"
cd ${ROOT}

# Build the core extensions with coverage enabled
python setup.py build_ext --export-compile-commands --enable-coverage

# Build the package
python setup.py build

# Run the tests in coverage mode generating the coverage report and create the
# JUnitXML report
pytest -q --cov=build --cov-report=xml:build/coverage_python.xml --junit-xml=build/pybind.xml

# Convert the pytest-cov report to lcov format
coverage lcov -o build/coverage_python.info

# The CMake configuration is already done by the build script in the
# BUILD_TEMP_DIR
cd ${BUILD_TEMP_DIR}

# C++ build & test
make test_all -j ${THREADS}

# Capture the C++ coverage data of all the targets at once. The unit tests and
# the third-party libraries are excluded from the capture: they are not part of
# the report, and they account for most of the data to process. The files that
# were never executed (.gcno without .gcda) are reported with no coverage.
lcov ${LCOV_FLAGS} --capture --all --directory . --base-directory "${ROOT}" \
    --no-external --parallel ${THREADS} \
    --exclude "${ROOT}/cxx/tests/*" --exclude "${ROOT}/third_party/*" \
    -o ../coverage_cpp.info

# Go back to the build directory ${ROOT}/build
cd ..

# Merge the two coverage reports
lcov ${LCOV_FLAGS} -a coverage_cpp.info -a coverage_python.info -o coverage.info

# Clean the source file paths in the coverage report
sed -i 's|SF:build/lib\.[^/]*/|SF:|g' coverage.info

# Remove the Python unit tests from the final coverage
lcov ${LCOV_FLAGS} --remove coverage.info "pyinterp/tests/*" -o coverage.info

# Generate the html report
cd ${ROOT}
genhtml ${LCOV_FLAGS} build/coverage.info --output-directory build/htmllcov --prefix "${ROOT}"

# Show the coverage
python scripts/coverage.py build/coverage.info
