#!/bin/bash
# Copyright (c) 2025 CNES.
#
# This software is distributed by the CNES under a proprietary license.
# It is not public and cannot be redistributed or used without permission.
set -e

# Get working directory of this script
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT=$(realpath ${ROOT}/..)

# Get the number of threads
THREADS=$(getconf _NPROCESSORS_ONLN)

# Get the build temp directory generated by the build script
BUILD_TEMP_DIR=$(python scripts/show_temp_build_dir.py)

# Ensure CMake finds the conda gcov instead of system gcov
# The conda compiler is x86_64-conda-linux-gnu-gcc but gcov is named
# x86_64-conda-linux-gnu-gcov, while CMake-codecov searches for gcov-${VERSION}
CONDA_GCOV=$(which x86_64-conda-linux-gnu-gcov 2>/dev/null)
if [[ -n "${CONDA_GCOV}" ]]; then
    CONDA_BIN_DIR=$(dirname "${CONDA_GCOV}")
    GCC_MAJOR=$(x86_64-conda-linux-gnu-gcc -dumpversion | cut -d. -f1)
    
    # Create symlinks if they don't exist
    if [[ ! -e "${CONDA_BIN_DIR}/gcov-${GCC_MAJOR}" ]]; then
        ln -s "${CONDA_GCOV}" "${CONDA_BIN_DIR}/gcov-${GCC_MAJOR}"
        echo "Created symlink: gcov-${GCC_MAJOR} -> ${CONDA_GCOV}"
    fi
    if [[ ! -e "${CONDA_BIN_DIR}/gcov" ]]; then
        ln -s "${CONDA_GCOV}" "${CONDA_BIN_DIR}/gcov"
        echo "Created symlink: gcov -> ${CONDA_GCOV}"
    fi
fi

# Generate the coverage report
echo "Generating coverage report"
echo "-------------------------------------------------------------------------"
echo "ROOT:           ${ROOT}"
echo "THREADS:        ${THREADS}"
echo "BUILD_TEMP_DIR: ${BUILD_TEMP_DIR}"
echo "-------------------------------------------------------------------------"
cd ${ROOT}

# Build the core extensions with coverage enabled
python setup.py build_ext --export-compile-commands --enable-coverage

# Build the package
python setup.py build

# Run the tests in coverage mode generating the coverage report and create the
# JUnitXML report
pytest -q --cov=build --cov-report=xml:build/coverage_python.xml --junit-xml=build/pybind.xml

# Convert the pytest-cov report to lcov format
coverage lcov -o build/coverage_python.info

# The CMake configuration is already done by the build script in the
# BUILD_TEMP_DIR
cd ${BUILD_TEMP_DIR}

# C++ build & test
make test_all -j ${THREADS}
make lcov -j ${THREADS}
lcov --extract  lcov/data/capture/all_targets.info.raw  "*" -o ../coverage_cpp.info

# Go back to the build directory ${ROOT}/build
cd ..

# Merge the two coverage reports
lcov -a coverage_cpp.info -a coverage_python.info -o coverage.info

# Clean the source file paths in the coverage report
sed -i 's|SF:build/lib\.[^/]*/|SF:|g' coverage.info

# Remove unwanted paths from the final coverage (tests, third_party)
lcov --remove coverage.info "${ROOT}/cxx/tests/*" "${ROOT}/third_party/*" "pyinterp/tests/*" -o coverage.info

# Generate the html report
cd ${ROOT}
genhtml build/coverage.info --output-directory build/htmllcov --prefix "${ROOT}"

# Show the coverage
python scripts/coverage.py build/htmllcov/index.html
