from typing import overload

from ....type_hints import NDArray1DBool, NDArray1DFloat64
from .. import geographic
from . import (
    Box,
    LineString,
    MultiLineString,
    MultiPoint,
    MultiPolygon,
    Point,
    Polygon,
    Ring,
    Segment,
    _Concept,
)

def area(
    geometry: _Concept,
) -> float: ...
def azimuth(
    point1: Point,
    point2: Point,
) -> float: ...
def buffer(
    geometry: _Concept,
    distance_strategy: DistanceSymmetric | DistanceAsymmetric,
    join_strategy: JoinRound | JoinMiter,
    end_strategy: EndRound | EndFlat,
    point_strategy: PointCircle | PointSquare,
) -> MultiPolygon: ...
def centroid(geometry: _Concept) -> Point: ...
def clear(geometry: _Concept) -> None: ...
def closest_points(
    geometry1: LineString
    | MultiLineString
    | MultiPoint
    | MultiPolygon
    | Polygon,
    geometry2: LineString
    | MultiLineString
    | MultiPoint
    | MultiPolygon
    | Polygon,
) -> Segment: ...
@overload
def convert_to_geographic(geometry: Point) -> geographic.Point: ...
@overload
def convert_to_geographic(geometry: Segment) -> geographic.Segment: ...
@overload
def convert_to_geographic(geometry: Box) -> geographic.Box: ...
@overload
def convert_to_geographic(geometry: LineString) -> geographic.LineString: ...
@overload
def convert_to_geographic(geometry: Ring) -> geographic.Ring: ...
@overload
def convert_to_geographic(geometry: Polygon) -> geographic.Polygon: ...
@overload
def convert_to_geographic(geometry: MultiPoint) -> geographic.MultiPoint: ...
@overload
def convert_to_geographic(
    geometry: MultiLineString,
) -> geographic.MultiLineString: ...
@overload
def convert_to_geographic(
    geometry: MultiPolygon,
) -> geographic.MultiPolygon: ...
def convex_hull(geometry: _Concept) -> Polygon: ...
def correct(geometry: _Concept) -> None: ...
@overload
def covered_by(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: Segment) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: LineString) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: MultiPoint) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: MultiLineString) -> bool: ...
@overload
def covered_by(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: Box, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: Box, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: Box, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: Box, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: MultiLineString) -> bool: ...
@overload
def covered_by(geometry1: LineString, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: Ring, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: Ring, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: Ring, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: Ring, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: Polygon, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: Polygon, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: Segment) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: LineString) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: MultiPoint) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: MultiLineString) -> bool: ...
@overload
def covered_by(geometry1: MultiPoint, geometry2: MultiPolygon) -> bool: ...
@overload
def covered_by(geometry1: MultiLineString, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: MultiLineString, geometry2: LineString) -> bool: ...
@overload
def covered_by(geometry1: MultiLineString, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: MultiLineString, geometry2: Polygon) -> bool: ...
@overload
def covered_by(
    geometry1: MultiLineString, geometry2: MultiLineString
) -> bool: ...
@overload
def covered_by(
    geometry1: MultiLineString, geometry2: MultiPolygon
) -> bool: ...
@overload
def covered_by(geometry1: MultiPolygon, geometry2: Box) -> bool: ...
@overload
def covered_by(geometry1: MultiPolygon, geometry2: Ring) -> bool: ...
@overload
def covered_by(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def covered_by(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
@overload
def crosses(geometry1: Point, geometry2: LineString) -> bool: ...
@overload
def crosses(geometry1: Point, geometry2: Ring) -> bool: ...
@overload
def crosses(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def crosses(geometry1: Point, geometry2: MultiLineString) -> bool: ...
@overload
def crosses(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: Point) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: Ring) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: MultiLineString) -> bool: ...
@overload
def crosses(geometry1: LineString, geometry2: MultiPolygon) -> bool: ...
@overload
def crosses(geometry1: Ring, geometry2: Point) -> bool: ...
@overload
def crosses(geometry1: Polygon, geometry2: Point) -> bool: ...
@overload
def crosses(geometry1: MultiLineString, geometry2: Point) -> bool: ...
@overload
def crosses(geometry1: MultiLineString, geometry2: LineString) -> bool: ...
@overload
def crosses(geometry1: MultiLineString, geometry2: Ring) -> bool: ...
@overload
def crosses(geometry1: MultiLineString, geometry2: Polygon) -> bool: ...
@overload
def crosses(
    geometry1: MultiLineString, geometry2: MultiLineString
) -> bool: ...
@overload
def crosses(geometry1: MultiLineString, geometry2: MultiPolygon) -> bool: ...
@overload
def crosses(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
@overload
def densify(geometry: LineString, max_distance: float) -> LineString: ...
@overload
def densify(geometry: Ring, max_distance: float) -> Ring: ...
@overload
def densify(geometry: Polygon, max_distance: float) -> Polygon: ...
@overload
def densify(
    geometry: MultiLineString, max_distance: float
) -> MultiLineString: ...
@overload
def densify(geometry: MultiPolygon, max_distance: float) -> MultiPolygon: ...
@overload
def difference(geometry1: Ring, geometry2: Ring) -> list[Polygon]: ...
@overload
def difference(geometry1: Ring, geometry2: Polygon) -> list[Polygon]: ...
@overload
def difference(geometry1: Polygon, geometry2: Ring) -> list[Polygon]: ...
@overload
def difference(geometry1: Polygon, geometry2: Polygon) -> list[Polygon]: ...
@overload
def difference(geometry1: MultiPolygon, geometry2: Ring) -> list[Polygon]: ...
@overload
def difference(
    geometry1: MultiPolygon, geometry2: Polygon
) -> list[Polygon]: ...
@overload
def difference(
    geometry1: MultiPolygon, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def difference(geometry1: Ring, geometry2: MultiPolygon) -> list[Polygon]: ...
@overload
def difference(
    geometry1: Polygon, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def disjoint(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def disjoint(geometry1: Point, geometry2: Box) -> bool: ...
@overload
def disjoint(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def disjoint(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def disjoint(geometry1: Box, geometry2: Point) -> bool: ...
@overload
def disjoint(geometry1: Box, geometry2: Box) -> bool: ...
@overload
def disjoint(geometry1: Box, geometry2: Polygon) -> bool: ...
@overload
def disjoint(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def disjoint(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def disjoint(geometry1: LineString, geometry2: Box) -> bool: ...
@overload
def disjoint(geometry1: Polygon, geometry2: Point) -> bool: ...
@overload
def disjoint(geometry1: Polygon, geometry2: Box) -> bool: ...
@overload
def disjoint(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def disjoint(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def disjoint(geometry1: MultiPolygon, geometry2: Point) -> bool: ...
@overload
def disjoint(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def disjoint(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
@overload
def distance(geometry1: Point, geometry2: Point) -> float: ...
@overload
def distance(geometry1: Point, geometry2: Box) -> float: ...
@overload
def distance(geometry1: Point, geometry2: Polygon) -> float: ...
@overload
def distance(geometry1: Point, geometry2: MultiPolygon) -> float: ...
@overload
def distance(geometry1: Box, geometry2: Point) -> float: ...
@overload
def distance(geometry1: Box, geometry2: Box) -> float: ...
@overload
def distance(geometry1: Box, geometry2: Polygon) -> float: ...
@overload
def distance(geometry1: LineString, geometry2: LineString) -> float: ...
@overload
def distance(geometry1: LineString, geometry2: Polygon) -> float: ...
@overload
def distance(geometry1: LineString, geometry2: Box) -> float: ...
@overload
def distance(geometry1: Polygon, geometry2: Point) -> float: ...
@overload
def distance(geometry1: Polygon, geometry2: Box) -> float: ...
@overload
def distance(geometry1: Polygon, geometry2: Polygon) -> float: ...
@overload
def distance(geometry1: Polygon, geometry2: MultiPolygon) -> float: ...
@overload
def distance(geometry1: MultiPolygon, geometry2: Point) -> float: ...
@overload
def distance(geometry1: MultiPolygon, geometry2: Polygon) -> float: ...
@overload
def distance(geometry1: MultiPolygon, geometry2: MultiPolygon) -> float: ...
def envelope(geometry: _Concept) -> Box: ...
@overload
def equals(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def equals(geometry1: Segment, geometry2: Segment) -> bool: ...
@overload
def equals(geometry1: Box, geometry2: Box) -> bool: ...
@overload
def equals(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def equals(geometry1: Ring, geometry2: Ring) -> bool: ...
@overload
def equals(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def equals(geometry1: MultiPoint, geometry2: MultiPoint) -> bool: ...
@overload
def equals(geometry1: MultiLineString, geometry2: MultiLineString) -> bool: ...
@overload
def equals(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
def for_each_point_covered_by(
    source: MultiPoint | LineString | Ring,
    container: Box | Ring | Polygon | MultiPolygon,
) -> NDArray1DBool: ...
def for_each_point_distance(
    source: MultiPoint | LineString | Ring,
    container: Box | Ring | Polygon | MultiPolygon,
) -> NDArray1DFloat64: ...
def for_each_point_within(
    source: MultiPoint | LineString | Ring,
    container: Box | Ring | Polygon | MultiPolygon,
) -> NDArray1DBool: ...
def from_geojson(
    geojson: str,
) -> (
    Point | LineString | MultiLineString | MultiPoint | MultiPolygon | Polygon
): ...
def from_wkt(
    wkt: str,
) -> (
    Point
    | LineString
    | Ring
    | Polygon
    | MultiPoint
    | MultiLineString
    | MultiPolygon
): ...
@overload
def intersection(geometry1: Ring, geometry2: Ring) -> list[Polygon]: ...
@overload
def intersection(geometry1: Ring, geometry2: Polygon) -> list[Polygon]: ...
@overload
def intersection(geometry1: Polygon, geometry2: Ring) -> list[Polygon]: ...
@overload
def intersection(geometry1: Polygon, geometry2: Polygon) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: MultiPolygon, geometry2: Ring
) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: MultiPolygon, geometry2: Polygon
) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: MultiPolygon, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: Ring, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: Polygon, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def intersection(
    geometry1: LineString, geometry2: Ring
) -> list[LineString]: ...
@overload
def intersection(
    geometry1: LineString, geometry2: Polygon
) -> list[LineString]: ...
@overload
def intersection(
    geometry1: Ring, geometry2: LineString
) -> list[LineString]: ...
@overload
def intersection(
    geometry1: Polygon, geometry2: LineString
) -> list[LineString]: ...
@overload
def intersection(
    geometry1: LineString, geometry2: LineString
) -> list[Point]: ...
@overload
def intersects(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def intersects(geometry1: Point, geometry2: Box) -> bool: ...
@overload
def intersects(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def intersects(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def intersects(geometry1: Box, geometry2: Point) -> bool: ...
@overload
def intersects(geometry1: Box, geometry2: Box) -> bool: ...
@overload
def intersects(geometry1: Box, geometry2: Polygon) -> bool: ...
@overload
def intersects(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def intersects(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def intersects(geometry1: LineString, geometry2: Box) -> bool: ...
@overload
def intersects(geometry1: Polygon, geometry2: Point) -> bool: ...
@overload
def intersects(geometry1: Polygon, geometry2: Box) -> bool: ...
@overload
def intersects(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def intersects(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def intersects(geometry1: MultiPolygon, geometry2: Point) -> bool: ...
@overload
def intersects(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def intersects(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
def is_empty(geometry: _Concept) -> bool: ...
def is_simple(geometry: _Concept) -> bool: ...
@overload
def is_valid(geometry: _Concept, return_reason: bool) -> tuple[bool, str]: ...
@overload
def is_valid(geometry: _Concept) -> bool: ...
def length(geometry: _Concept) -> float: ...
def line_interpolate(
    geometry: LineString | Segment, distance: float
) -> Point: ...
def num_geometries(geometry: _Concept) -> int: ...
def num_interior_rings(geometry: _Concept) -> int: ...
def num_points(geometry: _Concept) -> int: ...
def num_segments(geometry: _Concept) -> int: ...
@overload
def overlaps(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def overlaps(geometry1: LineString, geometry2: MultiLineString) -> bool: ...
@overload
def overlaps(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def overlaps(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def overlaps(geometry1: MultiLineString, geometry2: LineString) -> bool: ...
@overload
def overlaps(
    geometry1: MultiLineString, geometry2: MultiLineString
) -> bool: ...
@overload
def overlaps(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def overlaps(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
def perimeter(geometry: _Concept) -> float: ...
@overload
def relate(geometry1: Point, geometry2: Point, mask: str) -> bool: ...
@overload
def relate(
    geometry1: LineString, geometry2: LineString, mask: str
) -> bool: ...
@overload
def relate(geometry1: Ring, geometry2: Ring, mask: str) -> bool: ...
@overload
def relate(geometry1: Ring, geometry2: Polygon, mask: str) -> bool: ...
@overload
def relate(geometry1: Polygon, geometry2: Ring, mask: str) -> bool: ...
@overload
def relate(geometry1: Polygon, geometry2: Polygon, mask: str) -> bool: ...
@overload
def relation(geometry1: Point, geometry2: Point) -> str: ...
@overload
def relation(geometry1: LineString, geometry2: LineString) -> str: ...
@overload
def relation(geometry1: Ring, geometry2: Ring) -> str: ...
@overload
def relation(geometry1: Ring, geometry2: Polygon) -> str: ...
@overload
def relation(geometry1: Polygon, geometry2: Ring) -> str: ...
@overload
def relation(geometry1: Polygon, geometry2: Polygon) -> str: ...
def reverse(geometry: _Concept) -> None: ...
@overload
def simplify(geometry: LineString, distance: float) -> LineString: ...
@overload
def simplify(geometry: Ring, distance: float) -> Ring: ...
@overload
def simplify(geometry: Polygon, distance: float) -> Polygon: ...
@overload
def simplify(
    geometry: MultiLineString, distance: float
) -> MultiLineString: ...
@overload
def simplify(geometry: MultiPolygon, distance: float) -> MultiPolygon: ...
def to_geojson(
    geometry: Point
    | LineString
    | Polygon
    | MultiPoint
    | MultiLineString
    | MultiPolygon,
) -> str: ...
def to_wkt(
    geometry: Point
    | LineString
    | Ring
    | Polygon
    | MultiPoint
    | MultiLineString
    | MultiPolygon,
) -> str: ...
@overload
def touches(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def touches(geometry1: Point, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: Point, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def touches(geometry1: Point, geometry2: MultiLineString) -> bool: ...
@overload
def touches(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def touches(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: LineString, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def touches(geometry1: LineString, geometry2: MultiLineString) -> bool: ...
@overload
def touches(geometry1: LineString, geometry2: MultiPolygon) -> bool: ...
@overload
def touches(geometry1: Ring, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: Ring, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: Ring, geometry2: Polygon) -> bool: ...
@overload
def touches(geometry1: Ring, geometry2: MultiLineString) -> bool: ...
@overload
def touches(geometry1: Ring, geometry2: MultiPolygon) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: Point) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: MultiLineString) -> bool: ...
@overload
def touches(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def touches(geometry1: MultiLineString, geometry2: Point) -> bool: ...
@overload
def touches(geometry1: MultiLineString, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: MultiLineString, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: MultiLineString, geometry2: Polygon) -> bool: ...
@overload
def touches(
    geometry1: MultiLineString, geometry2: MultiLineString
) -> bool: ...
@overload
def touches(geometry1: MultiLineString, geometry2: MultiPolygon) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: Point) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: LineString) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: Ring) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: MultiLineString) -> bool: ...
@overload
def touches(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...
@overload
def union(geometry1: Ring, geometry2: Ring) -> list[Polygon]: ...
@overload
def union(geometry1: Ring, geometry2: Polygon) -> list[Polygon]: ...
@overload
def union(geometry1: Polygon, geometry2: Ring) -> list[Polygon]: ...
@overload
def union(geometry1: Polygon, geometry2: Polygon) -> list[Polygon]: ...
@overload
def union(geometry1: MultiPolygon, geometry2: Ring) -> list[Polygon]: ...
@overload
def union(geometry1: MultiPolygon, geometry2: Polygon) -> list[Polygon]: ...
@overload
def union(
    geometry1: MultiPolygon, geometry2: MultiPolygon
) -> list[Polygon]: ...
@overload
def union(geometry1: Ring, geometry2: MultiPolygon) -> list[Polygon]: ...
@overload
def union(geometry1: Polygon, geometry2: MultiPolygon) -> list[Polygon]: ...
@overload
def union(
    geometry1: LineString, geometry2: LineString
) -> list[LineString]: ...
@overload
def union(
    geometry1: MultiLineString, geometry2: MultiLineString
) -> list[LineString]: ...
def unique(geometry: _Concept) -> None: ...
@overload
def within(geometry1: Point, geometry2: Point) -> bool: ...
@overload
def within(geometry1: Point, geometry2: Segment) -> bool: ...
@overload
def within(geometry1: Point, geometry2: Box) -> bool: ...
@overload
def within(geometry1: Point, geometry2: LineString) -> bool: ...
@overload
def within(geometry1: Point, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: Point, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: Point, geometry2: MultiPoint) -> bool: ...
@overload
def within(geometry1: Point, geometry2: MultiLineString) -> bool: ...
@overload
def within(geometry1: Point, geometry2: MultiPolygon) -> bool: ...
@overload
def within(geometry1: Box, geometry2: Box) -> bool: ...
@overload
def within(geometry1: LineString, geometry2: LineString) -> bool: ...
@overload
def within(geometry1: LineString, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: LineString, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: LineString, geometry2: MultiLineString) -> bool: ...
@overload
def within(geometry1: LineString, geometry2: MultiPolygon) -> bool: ...
@overload
def within(geometry1: Ring, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: Ring, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: Ring, geometry2: MultiPolygon) -> bool: ...
@overload
def within(geometry1: Polygon, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: Polygon, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: Polygon, geometry2: MultiPolygon) -> bool: ...
@overload
def within(geometry1: MultiLineString, geometry2: LineString) -> bool: ...
@overload
def within(geometry1: MultiLineString, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: MultiLineString, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: MultiLineString, geometry2: MultiLineString) -> bool: ...
@overload
def within(geometry1: MultiLineString, geometry2: MultiPolygon) -> bool: ...
@overload
def within(geometry1: MultiPolygon, geometry2: Ring) -> bool: ...
@overload
def within(geometry1: MultiPolygon, geometry2: Polygon) -> bool: ...
@overload
def within(geometry1: MultiPolygon, geometry2: MultiPolygon) -> bool: ...

class DistanceAsymmetric:
    def __init__(
        self, distance_left: float, distance_right: float
    ) -> None: ...

class DistanceSymmetric:
    def __init__(self, buffer_distance: float) -> None: ...

class EndFlat:
    def __init__(self) -> None: ...

class EndRound:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class JoinMiter:
    def __init__(self, miter_limit: float = ...) -> None: ...

class JoinRound:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class PointCircle:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class PointSquare:
    def __init__(self) -> None: ...
