#!/bin/bash
set -e

TMP_CONTENT_DIR=/tmp/pyinterp
mkdir -p $TMP_CONTENT_DIR
cp -r examples binder $TMP_CONTENT_DIR

find . -delete

GENERATED_NOTEBOOKS_DIR=.generated-notebooks
cp -r $TMP_CONTENT_DIR/examples $GENERATED_NOTEBOOKS_DIR

find $GENERATED_NOTEBOOKS_DIR -name '*.py' -exec sphx_glr_python_to_jupyter.py '{}' +
NON_NOTEBOOKS=$(find $GENERATED_NOTEBOOKS_DIR -type f | grep -v '\.ipynb')
rm -f $NON_NOTEBOOKS

mv $TMP_CONTENT_DIR/binder .
rm -rf $TMP_CONTENT_DIR

mkdir notebooks
ln -s ../$GENERATED_NOTEBOOKS_DIR notebooks/auto_examples
